spring:
  application:
    name: wtc-lodestone-hub
  datasource:
    url: jdbc:mariadb://localhost:3306/wtc_lodestone
    username: lodestone
    password: lodestone
  jpa:
    hibernate:
      jdbc:
        time_zone: UTC
      ddl-auto: validate
    open-in-view: false

lodestone:
  admins:
    - username: admin
      password: ${LODESTONE_ADMIN_PASSWORD:admin}
  heartbeat-retention-days: 7