package io.github.falphir.lodestone;

import net.neoforged.neoforge.common.ModConfigSpec;

public class Config {
    private static final ModConfigSpec.Builder BUILDER = new ModConfigSpec.Builder();

    public static final ModConfigSpec.BooleanValue ENABLED = BUILDER
            .comment("Master switch. If false, the mod does nothing.")
            .define("enabled", true);

    public static final ModConfigSpec.BooleanValue DRY_RUN = BUILDER
            .comment("If true, events are only logged, never sent to the hub. Useful for testing.")
            .define("dryRun", false);

    public static final ModConfigSpec.ConfigValue<String> HUB_URL = BUILDER
            .comment("Base URL of the WTC Lodestone hub, e.g. http://127.0.0.1:8080")
            .define("hubUrl", "http://127.0.0.1:8080", Config::isValidUrl);

    public static final ModConfigSpec.ConfigValue<String> SERVER_ID = BUILDER
            .comment("Unique id of this server on the network (lowercase letters, numbers, _ and -), e.g. genesis")
            .define("serverId", "", Config::isValidServerId);

    public static final ModConfigSpec.ConfigValue<String> TOKEN = BUILDER
            .comment("Auth token for this server, generated by the hub. Keep it secret.")
            .define("token", "");

    static final ModConfigSpec SPEC = BUILDER.build();

    /** True when the mod is enabled and has everything it needs to talk to the hub. */
    public static boolean isReady() {
        return ENABLED.get() && !SERVER_ID.get().isBlank() && !TOKEN.get().isBlank();
    }

    private static boolean isValidUrl(Object obj) {
        return obj instanceof String s && (s.startsWith("http://") || s.startsWith("https://"));
    }

    private static boolean isValidServerId(Object obj) {
        return obj instanceof String s && (s.isEmpty() || s.matches("[a-z0-9_-]+"));
    }
}