package io.github.falphir.lodestone;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The mod's config, read straight from the TOML file rather than through a loader's config API
 * (NeoForge's ModConfigSpec, Forge's ForgeConfigSpec, ...), so the same code runs on every loader.
 * The file is flat -- six keys, no sections -- which is why a parser this small is enough.
 * <p>
 * The format is the one ModConfigSpec used to write, so configs on servers that ran an earlier
 * version keep working untouched, tokens and all.
 */
public final class LodestoneConfig {

    public static final String FILE_NAME = "wtc_lodestone-common.toml";

    private static final String DEFAULT_HUB_URL = "http://127.0.0.1:8080";

    private static final String DEFAULT_FILE = """
            #Master switch. If false, the mod does nothing.
            enabled = true
            #If true, events are only logged, never sent to the hub. Useful for testing.
            dryRun = false
            #Base URL of the WTC Lodestone hub, e.g. http://127.0.0.1:8080
            hubUrl = "%s"
            #Unique id of this server on the network (lowercase letters, numbers, _ and -), e.g. genesis
            serverId = ""
            #Auth token for this server, generated by the hub. Keep it secret.
            token = ""
            #If true, this server's whitelist mirrors the network whitelist managed on the hub.
            #Local /whitelist add and remove changes are overwritten on the next sync (every minute).
            syncWhitelist = true
            #Kick message for players who are not on the whitelist. Empty keeps Minecraft's own
            #message. Use \\n for a line break.
            whitelistMessage = ""
            """.formatted(DEFAULT_HUB_URL);

    private static Values values = new Values(true, false, DEFAULT_HUB_URL, "", "", true, "");

    private LodestoneConfig() {}

    /** Every setting, as read from the file. */
    public record Values(boolean enabled, boolean dryRun, String hubUrl, String serverId, String token,
            boolean syncWhitelist, String whitelistMessage) {}

    public static boolean enabled() { return values.enabled(); }
    public static boolean dryRun() { return values.dryRun(); }
    public static String hubUrl() { return values.hubUrl(); }
    public static String serverId() { return values.serverId(); }
    public static String token() { return values.token(); }
    public static boolean syncWhitelist() { return values.syncWhitelist(); }

    /** Kick message for players who are not whitelisted, with line breaks already decoded. Blank means "leave vanilla's alone". */
    public static String whitelistMessage() { return values.whitelistMessage(); }

    /** True when the mod is enabled and has everything it needs to talk to the hub. */
    public static boolean isReady() {
        return enabled() && !serverId().isBlank() && !token().isBlank();
    }

    /** Reads {@value #FILE_NAME} from {@code configDir}, writing the commented default first if it's missing. */
    public static void load(Path configDir) {
        Path file = configDir.resolve(FILE_NAME);
        try {
            if (Files.notExists(file)) {
                Files.createDirectories(configDir);
                Files.writeString(file, DEFAULT_FILE);
                Lodestone.LOGGER.info("Wrote a default WTC Lodestone config to {}", file);
                return;
            }
            List<String> problems = new ArrayList<>();
            values = parse(Files.readAllLines(file), problems);
            problems.forEach(problem -> Lodestone.LOGGER.warn("WTC Lodestone config: {}", problem));
        } catch (IOException e) {
            Lodestone.LOGGER.error("Could not read the WTC Lodestone config at {} -- using defaults: {}", file, e.getMessage());
        }
    }

    /**
     * Parses the file's lines. Anything missing or rejected keeps its default and is reported in
     * {@code problems}, so one bad line can't stop the rest of the config from being read.
     */
    static Values parse(List<String> lines, List<String> problems) {
        Map<String, String> raw = new HashMap<>();
        for (String line : lines) {
            String trimmed = line.trim();
            if (trimmed.isEmpty() || trimmed.startsWith("#")) continue;
            int equals = trimmed.indexOf('=');
            if (equals < 0) {
                problems.add("ignoring line without a value: " + trimmed);
                continue;
            }
            raw.put(trimmed.substring(0, equals).trim(), unquote(trimmed.substring(equals + 1).trim()));
        }

        String hubUrl = string(raw, "hubUrl", DEFAULT_HUB_URL, problems,
                value -> value.startsWith("http://") || value.startsWith("https://"),
                "must start with http:// or https://");
        String serverId = string(raw, "serverId", "", problems,
                value -> value.matches("[a-z0-9_-]*"),
                "must be lowercase letters, numbers, _ and - only");

        return new Values(
                bool(raw, "enabled", true, problems),
                bool(raw, "dryRun", false, problems),
                hubUrl,
                serverId,
                string(raw, "token", "", problems, value -> true, ""),
                bool(raw, "syncWhitelist", true, problems),
                // the file is one line per key, so a multi-line kick message is written as \n
                string(raw, "whitelistMessage", "", problems, value -> true, "").replace("\\n", "\n"));
    }

    /** Strips the quotes TOML puts around string values; other values are left as they are. */
    private static String unquote(String value) {
        boolean quoted = value.length() >= 2
                && ((value.startsWith("\"") && value.endsWith("\"")) || (value.startsWith("'") && value.endsWith("'")));
        return quoted ? value.substring(1, value.length() - 1) : value;
    }

    private static boolean bool(Map<String, String> raw, String key, boolean fallback, List<String> problems) {
        String value = raw.get(key);
        if (value == null) return fallback;
        if (value.equalsIgnoreCase("true")) return true;
        if (value.equalsIgnoreCase("false")) return false;
        problems.add(key + " must be true or false, using " + fallback);
        return fallback;
    }

    private static String string(Map<String, String> raw, String key, String fallback, List<String> problems,
            java.util.function.Predicate<String> valid, String requirement) {
        String value = raw.get(key);
        if (value == null) return fallback;
        if (!valid.test(value)) {
            problems.add(key + " " + requirement + ", using \"" + fallback + "\"");
            return fallback;
        }
        return value;
    }
}
